## Importing Package

In [1]:
import numpy as np

Creating a function that creates an array of random variables

$a$ : Min Range of the outcomes

$b$ : Max Range of the outcomes

$size$: Total number of random variables

In [10]:
def uniform(a, b, size):
    return np.random.randint(a, b+1, size)

## Testing Uniform Function
- Testing the function with a toss of a coin, where the outcomes are $0 \text{ and } 1$ with equal probability (0 = Head, 1 = Tail)
- Testing the function with a roll of a dice, where the outcomes are $\lbrace 1, 2, 3, 4, 5, 6\rbrace$ with equal probability
- Testing the function with a pack of cards ($52$ cards), where the outcomes are $\lbrace \text{Ace } (1), 2, 3, 4, 5, 6, 7, 8, 9, 10, \text{ Jack } (11), \text{ Queen } (12), \text{ King } (13) \rbrace$ with equal probability
  -  The range of the outcomes will be from 1 to 52 and the outcome will be moduled by 13 to get the card.

# Toss of a coin
- Tossing $n$ times
  - Once
  - 10 times
  - 100 times

In [14]:
print(uniform(0, 1, 1))
print(uniform(0, 1, 10))
print(uniform(0, 1, 100))

[0]
[0 1 0 1 0 1 1 0 1 0]
[1 0 0 1 1 1 1 0 1 0 1 1 0 1 0 1 1 1 0 0 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 0 0
 1 0 0 1 0 0 1 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 0 0 0
 0 0 0 1 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 1 0 1 0 0 0 0]


# Throwing a dice
- Throwing $n$ times
  - Once
  - 10 times
  - 100 times

In [17]:
print(uniform(0, 6, 1))
print(uniform(0, 6, 10))
print(uniform(0, 6, 100))

[6]
[1 2 0 4 6 0 4 5 3 1]
[6 2 2 2 3 5 5 4 2 5 6 3 5 0 4 5 3 6 3 0 1 4 2 6 5 4 1 2 5 3 2 1 3 3 3 6 4
 4 5 0 5 2 3 6 2 4 5 3 4 3 3 5 1 2 1 1 3 1 4 1 5 0 6 2 2 3 4 2 5 4 4 3 1 3
 1 4 0 6 0 5 5 6 1 5 0 1 3 3 0 1 0 3 1 1 5 0 4 2 0 1]


# Picking a card from a deck of cards
- Picking $n$ times
  - Once
  - 10 times
  - 100 times

In [18]:
print(uniform(0, 52, 1))
print(uniform(0, 52, 10))
print(uniform(0, 52, 100))

[48]
[47 18 39 22  7 31 22  7 51 47]
[12  6 40 10  6 43 39 12 33 16  2 13 45 28 29 19 16 51  0 21 20 52 22 10
 12  9 42 44 39  3 14 31  9 44 51 29  8 47 37 35 50 32 38 44 23 47 26 34
 48 21 25  0 34 23  6 40 28 22  8 52  8 39  7  7  8 27 33 12 34  2  2 44
 44  8 38 38 15 41 49 27 50 37  5 43 10 42  6 52 31 43 36 43 13 35 46 43
 33 52  6 45]


# Monte Carlo Simulation - Estimating the probability by simulation
Monte Carlo simulation is a computational technique that uses random sampling to estimate the probability of different outcomes. It is often used in situations where it is difficult or impossible to calculate the probability analytically. The technique involves generating a large number of random samples and using these samples to estimate the probability of different outcomes. Monte Carlo simulation is widely used in finance, engineering, physics, and other fields to model complex systems and estimate the likelihood of different outcomes.

Higher the number of samples, more accurate the probability estimate will be. However, the computational cost of the simulation increases with the number of samples. Therefore, it is important to find a balance between accuracy and computational cost.

### Formula 
$$ \text{Probability} = \frac{\text{Number of times the event occured}}{\text{Total number of trials}}$$

### Monte Carlo Simulation for getting a prime number in a dice

- There are $3$ prime numbers between $1 \text{ and } 6 (2,3,5)$ the probability of getting a prime number is $3/6 = 0.5$

In [29]:
prime_count = 0
n = 1000000
for i in range(n):
    output = uniform(1, 6, 1)[0]
    if output == 2 or output == 3 or output == 5:
        prime_count += 1
print(prime_count/n)

0.499375


# Probability of getting a king in a deck of cards
- There are $4$ kings in a deck of cards, the probability of getting a king is $4/52 = 0.0769230769$

In [32]:
king_count = 0
n = 1000000
for i in range(n):
    output = uniform(1, 52, 1)[0]
    if output % 13 == 0:
        king_count += 1
print(king_count/n)

0.077077
